//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV
{
    using System;
    using System.Collections.Generic;
    
    public partial class TongKetKy
    {
        public int MaSV { get; set; }
        public int MaHK { get; set; }
        public Nullable<double> DiemTBC { get; set; }
        public Nullable<int> STCDKy { get; set; }
        public Nullable<int> STCD { get; set; }
        public string XepLoai { get; set; }
    
        public virtual HocKy HocKy { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
